### ISSUE TITLE
rbenv sudo command not working on ubuntu

### ISSUE THREAD

**Issue by igagen** [dcarley/rbenv-sudo#11]
I don't see sudo in the list of rbenv commands after installation. I'm running Ubuntu 14.04. Other installed plugins such as rbenv-build are working fine and show up in the command list.

Not sure if it's relevant, but here is my sudo config:

Defaults        env_reset
Defaults        mail_badpass
Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
root    ALL=(ALL:ALL) ALL
%admin ALL=(ALL) ALL
%sudo   ALL=(ALL:ALL) ALL

**Comment by SeanRoberts** [comment]
@igagen I'm having the same issue, did you solve this?
